---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: magento
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "keepitsecret"


---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9187"
    prometheus.io/scrape: "true"
  labels:
    app: mysql
  name: mysql
  namespace: magento
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: magento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: magento
        envFrom:
        - secretRef:
            name: mysql
        image: mysql:8.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 300m
            memory: 1Gi
        name: db
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/data
          name: mysql-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
      serviceAccountName: magento-sa
      terminationGracePeriodSeconds: 60
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: mysql
      name: mysql-data
      namespace: magento
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: pv-ssd-root-ec-sc