
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magento-app-data
  namespace: magento
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs


---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9187"
    prometheus.io/scrape: "true"
  labels:
    app: magento-app
  name: magento-app
  namespace: magento
spec:
  ports:
  - name: magento-app
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: magento-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento-app
  namespace: magento
spec:
  minReadySeconds: 25
  replicas: 1
  selector:
    matchLabels:
      app: magento-app
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: magento-app
    spec:
      containers:
      - name: app
        image: whyxn/magento-k8:2.4.4-v2
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 20
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 10
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 20
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 10
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html/magento
          name: data-vol
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
      serviceAccountName: magento-sa
      terminationGracePeriodSeconds: 5
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: magento-app-data